#!/usr/bin/env bash
# Sync vendored skills from obra/superpowers at the pinned SHA.
#
# Why a vendor-with-override pattern (not a submodule, not a subtree):
# we MUST rewrite each skill's `description:` to anchor it to the
# CERN domain (cliff prevention — generic "you MUST verify" descriptions
# will out-shout our domain skills in the router). Submodules and
# subtrees both break when we modify the tracked content. Vendoring
# with a per-skill frontmatter override gives us full control of the
# routing-relevant fields while pulling the body unchanged from
# upstream.
#
# Layout:
#
#   script/superpowers/
#     lock                                  ← pinned upstream SHA
#     <skill>.frontmatter.md                ← our override (one per skill)
#
# Output:
#
#   config/skills/operational/<skill>/SKILL.md
#
# Usage (from repo root):
#
#   ./script/sync-superpowers.sh           # rebuild from the pinned SHA
#   ./script/sync-superpowers.sh --check   # dry-run; report drift
#
# To bump the pin: edit `sha=` and `date=` in script/superpowers/lock,
# re-run the script, review the diff, commit.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOCK="$REPO_ROOT/script/superpowers/lock"
OVERRIDE_DIR="$REPO_ROOT/script/superpowers"
OUT_DIR="$REPO_ROOT/config/skills/operational"

CHECK_ONLY=0
if [[ "${1:-}" == "--check" ]]; then
    CHECK_ONLY=1
fi

if [[ ! -f "$LOCK" ]]; then
    echo "error: missing $LOCK" >&2
    exit 1
fi

# Read repo + sha + date from the lock file. Plain `key=value` lines.
repo=""
sha=""
date=""
while IFS='=' read -r key value; do
    [[ -z "$key" || "$key" =~ ^# ]] && continue
    case "$key" in
        repo) repo="$value" ;;
        sha)  sha="$value"  ;;
        date) date="$value" ;;
    esac
done < "$LOCK"

if [[ -z "$repo" || -z "$sha" || -z "$date" ]]; then
    echo "error: lock is missing repo / sha / date" >&2
    exit 1
fi

# Translate https://github.com/<org>/<name> → raw URL prefix.
raw_prefix="${repo/github.com/raw.githubusercontent.com}/$sha"

echo "Syncing from $repo @ $sha ($date)"

shopt -s nullglob
overrides=("$OVERRIDE_DIR"/*.frontmatter.md)
if [[ ${#overrides[@]} -eq 0 ]]; then
    echo "error: no override files in $OVERRIDE_DIR" >&2
    exit 1
fi

drift=0
for override in "${overrides[@]}"; do
    skill="$(basename "$override" .frontmatter.md)"
    upstream_url="$raw_prefix/skills/$skill/SKILL.md"
    out_skill_dir="$OUT_DIR/$skill"
    out_file="$out_skill_dir/SKILL.md"

    echo
    echo "  $skill"
    echo "    upstream: $upstream_url"
    echo "    output:   ${out_file#$REPO_ROOT/}"

    # Fetch upstream body. Fail if 404 or non-2xx.
    tmp_upstream="$(mktemp)"
    trap 'rm -f "$tmp_upstream"' EXIT
    if ! curl -fsSL "$upstream_url" -o "$tmp_upstream"; then
        echo "    error: failed to fetch upstream $upstream_url" >&2
        exit 1
    fi

    # Strip upstream's frontmatter: skip everything until the second
    # `---` line, then emit the rest verbatim.
    body="$(awk 'BEGIN{n=0} /^---[[:space:]]*$/{n++; next} n>=2{print}' "$tmp_upstream")"

    if [[ -z "$body" ]]; then
        echo "    error: upstream body is empty after stripping frontmatter" >&2
        exit 1
    fi

    header="<!-- Vendored from $repo @ $sha on $date.
     Do not edit this file directly; modify
     script/superpowers/$skill.frontmatter.md and re-run
     script/sync-superpowers.sh. -->"

    new_content="$(cat "$override")
$header
$body"

    if [[ $CHECK_ONLY -eq 1 ]]; then
        if [[ ! -f "$out_file" ]] || ! diff -q <(echo "$new_content") "$out_file" >/dev/null 2>&1; then
            echo "    DRIFT: would change ${out_file#$REPO_ROOT/}"
            drift=1
        else
            echo "    ok"
        fi
    else
        mkdir -p "$out_skill_dir"
        printf '%s\n' "$new_content" > "$out_file"
        echo "    written"
    fi

    rm -f "$tmp_upstream"
    trap - EXIT
done

if [[ $CHECK_ONLY -eq 1 ]]; then
    if [[ $drift -ne 0 ]]; then
        echo
        echo "Drift detected. Re-run without --check to update."
        exit 2
    fi
    echo
    echo "No drift."
fi
